name: Lint, analyse and test on highest supported PHP version

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'highest'
          tools: composer

      - uses: actions/checkout@v6
      - run: composer install --no-progress
      - run: composer run check-syntax
      - run: composer run check-codestyle
      - run: composer run static-analysis
      - run: composer run test
