name: Check PHP syntax on lowest supported PHP version

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
          ini-file: development

      - uses: actions/checkout@v6
      - run: composer run check-syntax
